In [1]:
import numpy as np

In [2]:
layers = [1, 3, 1]
biases = [np.random.randn(x, 1) for x in layers[1:]]
weights = [np.random.randn(x, y) for x, y in zip(layers[:-1], layers[1:])]

In [47]:
type(weights)
weights.T

AttributeError: 'list' object has no attribute 'T'

In [39]:
a = np.reshape(np.array([7]), (1, 1))
a.shape

(1, 1)

In [37]:
np.dot(weights[0].T, a)

array([[ 1.57908877],
       [-0.07461893],
       [ 4.05838147]])

In [45]:
for b, w in zip(biases[:-1], weights[:-1]):
    # a = np.dot(w.T, a) + b
    print(type(w))

<class 'numpy.ndarray'>


In [49]:
for b, w in zip(biases[:-1], weights[:-1]):
    # a = np.dot(w.T, a) + b
    print(w.T)

[[ 0.22558411]
 [-0.01065985]
 [ 0.57976878]]


In [28]:
a

array([[0.49120474],
       [0.6537592 ],
       [0.45751857]])

In [16]:
for b, w in zip(biases, weights):
    print(w)

[[ 0.22558411 -0.01065985  0.57976878]]
[[ 1.1846444 ]
 [-1.04391106]
 [-0.39681815]]


In [17]:
[np.random.randn(x, y) for x, y in zip(layers[:-1], layers[1:])]

[array([[ 0.93639985, -0.54575449, -0.18644033]]),
 array([[ 1.1236829 ],
        [-0.66217403],
        [-0.54062757]])]

In [19]:
[(x, y) for x, y in zip(layers[:-1], layers[1:])]

[(1, 3), (3, 1)]

In [20]:
biases

[array([[ 0.06383174],
        [-0.57093633],
        [ 0.19537479]]),
 array([[0.16943631]])]

In [32]:
layers[:-1]

[1, 3]

In [31]:
biases

[array([[ 0.06383174],
        [-0.57093633],
        [ 0.19537479]]),
 array([[0.16943631]])]

In [33]:
layers[1:]

[3, 1]

In [56]:
x = np.linspace(0, 2 * np.pi, 100)
x.shape

(100,)

In [57]:
import matplotlib.pyplot as plt

In [ ]:
fig, ax = plt.subplots()
# ax.plot(x, y, color = "green")
ax.scatter(x, y, color = "red")
ax.plot(test_x, prediction, color = "green")